using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TopDownCharacterContoller : MonoBehaviour
{
    public event Action<Vector2> OnMoveEvent;
    public event Action<Vector2> OnLookEvent;

    public void CallMoveEvent(Vector2 direction)
    {
        OnMoveEvent?.Invoke(direction);
    }

    public void CallLookEvent(Vector2 direction)
    {
        OnLookEvent?.Invoke(direction);
    }
}

////public float speed = 5f;

//// Start is called before the first frame update
//void Start()
//{

//}

//// Update is called once per frame
//void Update()
//{
//    //float x = Input.GetAxisRaw("Horizontal");// 가로
//    //float y = Input.GetAxisRaw("Vertical");// 세로

//    //transform.position += new Vector3(x, y) * speed * Time.deltaTime;
//}
